version: '3.7'

services:
  docs:
    build:
      context: .
    volumes:
      - ./build:/docs/build
      - ./source:/docs/source
      - ../PowerSimData:/PowerSimData
      - ../PreREISE:/PreREISE
      - ../PostREISE:/PostREISE
