name: Build and publish docs

on: [push, workflow_dispatch]

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          path: docs

      - name: Checkout PostREISE
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PostREISE
          path: PostREISE

      - name: Checkout PowerSimData
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PowerSimData
          path: PowerSimData

      - name: Checkout PreREISE
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/PreREISE
          path: PreREISE

      - name: Checkout REISE.jl
        uses: actions/checkout@v2
        with:
          repository: Breakthrough-Energy/REISE.jl
          path: REISE.jl

      - name: Build docs
        run: docker-compose up
        working-directory: docs

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
