name: Check writing style

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    name: Write good
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npx write-good --parse source/dev/*.md || true
